# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: HT CI

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "14 2,10,18 * * *"
  push:
    paths: [.github/workflows/ht.yml]
    branches: [main]

concurrency:
  group: ht

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install requirements
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
          sudo apt update 
          sudo apt install aria2 ffmpeg wireguard python
          sudo npm i -g @mehulagg/w3

      - name: install ipfs
        run: |
          wget https://github.com/ipfs/go-ipfs/releases/download/v0.10.0/go-ipfs_v0.10.0_linux-amd64.tar.gz
          tar -xvzf go-ipfs_v0.10.0_linux-amd64.tar.gz
          cd go-ipfs
          sudo bash install.sh
          ipfs --version
          ipfs init

      - run: git clone https://github.com/jonyg80/ht-num.git

      - name: run script
        run: |
          cd ht-num
          for ((START = $(cat num.txt) ; START <= 701 ;)); do 
            cd /home/runner/work/reimagined-octo-spoon/reimagined-octo-spoon/ht-num
            rm -r vid || true
            START=$(($START+1))
            echo "**#* START = ${START}  *#**"
            mkdir vid
            cd vid
            yt-dlp --compat-options filename -i --playlist-items=${START} --write-thumbnail --external-downloader=aria2c -- "${{ secrets.HT_URL }}" || continue
            cd ..
            CID=$(ipfs add --cid-version 1 --pin=false --quieter --trickle --recursive ./vid)
            echo "CID = ${CID}"
            ipfs dag export --progress=false -- ${CID} > vid.car
            w3 put-car ./vid.car --token ${{ secrets.WEB3_TOKEN }}
            echo $START > num.txt
            git config user.name "jonyg80"
            git config user.email "${{ secrets.GIT_EMAIL }}"
            git add num.txt
            git commit -m "increment $START"
            git push https://jonyg80:${{ secrets.GIT_TOKEN }}@github.com/jonyg80/ht-num.git main
            rm -r vid
            rm vid.car
            ipfs repo gc -q
            df -h

            if (( $START >= 700))
            then
              START=0
            fi
          done
