# This is a basic workflow to help you get started with Actions

name: IDs CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths: [.github/workflows/ids.yml]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        list_url: ["video","video?o=mv","video?o=cm","video/search?search=sister&o=mv","video/search?search=daughter&o=mv","video/search?search=massage&o=mv"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      - name: install requirements
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
        
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: yt-dlp --no-warnings --print "%(id)s" -- "${{ secrets.URL }}/${{ matrix.list_url }}" > videos_ids.txt
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: videos_ids.txt
      
