name: Test One CI

on:
  workflow_dispatch:
#   schedule:
#     - cron: "30 1,7,13,19 * * *"
  push:
    paths: [.github/workflows/test_one.yml]
    branches: [main]

concurrency:
  group: Testone
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        num: [11]

    steps:
      - uses: actions/checkout@v2
      
      - name: Ip address
        run: host myip.opendns.com resolver1.opendns.com

      - name: install requirements
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
          sudo apt update 
          sudo apt install ffmpeg
          sudo npm i -g @mehulagg/nft_cli

      - name: install ipfs
        run: |
          wget https://github.com/ipfs/go-ipfs/releases/download/v0.11.0/go-ipfs_v0.11.0_linux-amd64.tar.gz
          tar -xvzf go-ipfs_v0.11.0_linux-amd64.tar.gz
          cd go-ipfs
          sudo bash install.sh
          ipfs --version
          ipfs init

      - run: git clone https://jonyg80:${{ secrets.GIT_TOKEN }}@github.com/web3-num/${{ matrix.num }}.git

      - name: run script
        env:
          REPO_DIR: /home/runner/work/reimagined-octo-spoon/reimagined-octo-spoon/${{ matrix.num }}
          SECRET_NAME: "NFT_TOKEN_${{ matrix.num }}"
        run: |
          cd $REPO_DIR
          url_list=$(cat videos_links_${{ matrix.num }}.txt)
          url_array=($url_list)
          START=$(($(cat num.txt)+1))
          for i in $(seq $START 20001);do
            yt-dlp -i --write-thumbnail -o "%(id)s/%(title)s-%(id)s.%(ext)s" \
            --exec 'CID=$(ipfs add --cid-version 1 --pin=false --quieter --trickle --recursive "./%(id)s") && \
            echo "CID = ${CID}" && \
            ipfs dag export --progress=false -- ${CID} > "./%(id)s.car" && \
            nft put-car "./%(id)s.car" --token ${{ secrets[env.SECRET_NAME] }} && \
            rm -r "./%(id)s" && \
            rm "./%(id)s.car" && \
            ipfs repo gc > removed_cids.txt && \
            cd $REPO_DIR && \
            echo "Repo directory"
            echo $REPO_DIR
            echo "Number"
            echo %(i)s' \
            -- ${url_array[i]} || true
          done
